### ISSUE TITLE
Ignore release command?

### ISSUE THREAD

**Issue by theflow** [DarthSim/hivemind#5]
Hi,

thanks for hivemind, I really enjoy using it!

I've recently added a `release` command to my Procfile (see https://devcenter.heroku.com/articles/release-phase). And now hivemind stops working as it recognizes the task exit and shuts everything down.

Would it make sense to ignore `release` by default? That's the behavior of `heroku local`

Cheers,
Florian

**Comment by DarthSim** [comment]
Hi,
I don't think it will be predictable behavior if hivemind will ignore hardcoded process names. You can specify processes which you want to run with `-l` param. As for our team, we have two procfiles - one for production and one for development.
Have you tried [overmind](https://github.com/DarthSim/overmind)? With it, you can specify processes which can die after execution without stopping the rest ones.

**Comment by ivanovv** [comment]
I +1 @theflow suggestion.

> I don't think it will be predictable behavior if hivemind will ignore hardcoded process names

We can print a warning in red that `release` process is ignored and the workaround for that will be to use `-l` param.

If you are strictly against this,maybe you can add an option to ignore some processes then? Using `-l` to specify 3 processes (if we have 4 in `Procfile`) looks cumbersome to me. Something like `-i` `--ignore`, so that the final command will be like 
```
$> hivemind -i release
```
